export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const UPLOAD_SUCCESSFUL = 'UPLOAD_SUCCESSFUL';
export const UPLOAD_FAIL = 'UPLOAD_FAIL';
export const VERIFICATION_LINK_SEND = 'VERIFICATION_LINK_SEND';
export const VERIFICATION_LINK_NOT_SEND = 'VERIFICATION_LINK_NOT_SEND';
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED';
export const PASSWORD_NOT_SET = 'PASSWORD_NOT_SET';

